insert into APP.CITIES(province_id,name) values(1,'Miramichi');
insert into APP.CITIES(province_id,name) values(1,'Waldeck');
insert into APP.CITIES(province_id,name) values(1,'Walpole');
insert into APP.CITIES(province_id,name) values(1,'Jonquiere');
insert into APP.CITIES(province_id,name) values(1,'Salmon Arm');
insert into APP.CITIES(province_id,name) values(1,'Nigadoo');
insert into APP.CITIES(province_id,name) values(1,'Brancepeth');
insert into APP.CITIES(province_id,name) values(1,'Dalhousie');
insert into APP.CITIES(province_id,name) values(1,'Fort St John');
insert into APP.CITIES(province_id,name) values(1,'Beaufort');
insert into APP.CITIES(province_id,name) values(2,'Glenora');
insert into APP.CITIES(province_id,name) values(2,'Joliette');
insert into APP.CITIES(province_id,name) values(2,'Pipun');
insert into APP.CITIES(province_id,name) values(2,'Glentworth');
insert into APP.CITIES(province_id,name) values(3,'Tribune');
insert into APP.CITIES(province_id,name) values(3,'Properity');
insert into APP.CITIES(province_id,name) values(3,'Crediton');
insert into APP.CITIES(province_id,name) values(3,'Pittsburgh');
insert into APP.CITIES(province_id,name) values(3,'Truro');
insert into APP.CITIES(province_id,name) values(4,'Manitouaning');
insert into APP.CITIES(province_id,name) values(4,'Senneterre');
insert into APP.CITIES(province_id,name) values(4,'Amesdale');
insert into APP.CITIES(province_id,name) values(4,'Rutherglen');
insert into APP.CITIES(province_id,name) values(5,'Brandon');
insert into APP.CITIES(province_id,name) values(5,'Polwarth');
insert into APP.CITIES(province_id,name) values(5,'Beachburg');
insert into APP.CITIES(province_id,name) values(5,'Bodmin');
insert into APP.CITIES(province_id,name) values(5,'Dorion');
insert into APP.CITIES(province_id,name) values(6,'Barich');
insert into APP.CITIES(province_id,name) values(6,'Centerville');
insert into APP.CITIES(province_id,name) values(6,'Sunnybrook');
insert into APP.CITIES(province_id,name) values(7,'Goshen');
insert into APP.CITIES(province_id,name) values(7,'Orrville');
insert into APP.CITIES(province_id,name) values(8,'Rollet');
insert into APP.CITIES(province_id,name) values(8,'Goodlands');
insert into APP.CITIES(province_id,name) values(8,'Kispiox');
insert into APP.CITIES(province_id,name) values(8,'Sherridon');
insert into APP.CITIES(province_id,name) values(8,'Pike');
insert into APP.CITIES(province_id,name) values(9,'Yonker');
insert into APP.CITIES(province_id,name) values(9,'Chater');
insert into APP.CITIES(province_id,name) values(9,'Kessock');
insert into APP.CITIES(province_id,name) values(9,'Glace Bay');
insert into APP.CITIES(province_id,name) values(9,'Finmoore');
insert into APP.CITIES(province_id,name) values(10,'Jackfish');
insert into APP.CITIES(province_id,name) values(10,'Shamattawa');
insert into APP.CITIES(province_id,name) values(10,'Stanley');
insert into APP.CITIES(province_id,name) values(10,'Bentley');
insert into APP.CITIES(province_id,name) values(10,'Woburn');
insert into APP.CITIES(province_id,name) values(10,'Shoreacres');
insert into APP.CITIES(province_id,name) values(10,'Stormont');
insert into APP.CITIES(province_id,name) values(11,'Coatsburg');
insert into APP.CITIES(province_id,name) values(11,'Magas Arriba');
insert into APP.CITIES(province_id,name) values(11,'Au Sable');
insert into APP.CITIES(province_id,name) values(11,'Highmore');
insert into APP.CITIES(province_id,name) values(11,'Mart');
insert into APP.CITIES(province_id,name) values(11,'Clarence Center');
insert into APP.CITIES(province_id,name) values(11,'Tindall');
insert into APP.CITIES(province_id,name) values(12,'White Salmon');
insert into APP.CITIES(province_id,name) values(12,'Shueyville');
insert into APP.CITIES(province_id,name) values(12,'Talking Rock');
insert into APP.CITIES(province_id,name) values(12,'Rogers City');
insert into APP.CITIES(province_id,name) values(12,'Chelyan');
insert into APP.CITIES(province_id,name) values(12,'Buckhorn');
insert into APP.CITIES(province_id,name) values(12,'Bartelso');
insert into APP.CITIES(province_id,name) values(12,'Long Island');
insert into APP.CITIES(province_id,name) values(12,'West Scio');
insert into APP.CITIES(province_id,name) values(13,'Flora Vista');
insert into APP.CITIES(province_id,name) values(13,'New Post');
insert into APP.CITIES(province_id,name) values(13,'Shoshone');
insert into APP.CITIES(province_id,name) values(13,'Everett');
insert into APP.CITIES(province_id,name) values(13,'Black Forest');
insert into APP.CITIES(province_id,name) values(13,'Dorrington');
insert into APP.CITIES(province_id,name) values(13,'Alcoa');
insert into APP.CITIES(province_id,name) values(13,'Steeleville');
insert into APP.CITIES(province_id,name) values(13,'Crystal River');
insert into APP.CITIES(province_id,name) values(13,'McCullom Lake');
insert into APP.CITIES(province_id,name) values(14,'Marshfield Hills');
insert into APP.CITIES(province_id,name) values(15,'Stark City');
insert into APP.CITIES(province_id,name) values(16,'Hartsville');
insert into APP.CITIES(province_id,name) values(17,'Sand Springs');
insert into APP.CITIES(province_id,name) values(17,'Cochiti');
insert into APP.CITIES(province_id,name) values(18,'Kensett');
insert into APP.CITIES(province_id,name) values(19,'Henryville');
insert into APP.CITIES(province_id,name) values(20,'Sterlington');
insert into APP.CITIES(province_id,name) values(21,'Cascade');
insert into APP.CITIES(province_id,name) values(21,'Oscoda');
insert into APP.CITIES(province_id,name) values(22,'Suring');
insert into APP.CITIES(province_id,name) values(23,'Peeples Valley');
insert into APP.CITIES(province_id,name) values(24,'North Bay Shore');
insert into APP.CITIES(province_id,name) values(25,'Frenchtown');
insert into APP.CITIES(province_id,name) values(26,'Minersville');
insert into APP.CITIES(province_id,name) values(27,'Diamond Ridge');
insert into APP.CITIES(province_id,name) values(28,'Cowley');
insert into APP.CITIES(province_id,name) values(29,'Java');
insert into APP.CITIES(province_id,name) values(30,'Box Elder');
insert into APP.CITIES(province_id,name) values(31,'Owl Ranch');
insert into APP.CITIES(province_id,name) values(32,'Adair');
insert into APP.CITIES(province_id,name) values(33,'La Homa');
insert into APP.CITIES(province_id,name) values(34,'Linesville');
insert into APP.CITIES(province_id,name) values(35,'West Falls');

select * from APP.CITIES;
