insert into APP.PROVINCES(country_id,name) values (1,'Ontario');
insert into APP.PROVINCES(country_id,name) values (1,'Manitoba');
insert into APP.PROVINCES(country_id,name) values (1,'Saskatchewan');
insert into APP.PROVINCES(country_id,name) values (1,'Alberta');
insert into APP.PROVINCES(country_id,name) values (1,'British Columbia');
insert into APP.PROVINCES(country_id,name) values (1,'Québec');
insert into APP.PROVINCES(country_id,name) values (1,'New Brunswick');
insert into APP.PROVINCES(country_id,name) values (1,'Newfoundland and Labrador');
insert into APP.PROVINCES(country_id,name) values (1,'Prince Edward Island');
insert into APP.PROVINCES(country_id,name) values (1,'Nova Scotia');
insert into APP.PROVINCES(country_id,name) values (2,'Alabama');
insert into APP.PROVINCES(country_id,name) values (2,'Alaska');
insert into APP.PROVINCES(country_id,name) values (2,'Arizona');
insert into APP.PROVINCES(country_id,name) values (2,'Arkansas');
insert into APP.PROVINCES(country_id,name) values (2,'California');
insert into APP.PROVINCES(country_id,name) values (2,'Colorado');
insert into APP.PROVINCES(country_id,name) values (2,'Connecticut');
insert into APP.PROVINCES(country_id,name) values (2,'Delaware');
insert into APP.PROVINCES(country_id,name) values (2,'District Of Columbia');
insert into APP.PROVINCES(country_id,name) values (2,'Florida');
insert into APP.PROVINCES(country_id,name) values (2,'Georgia');
insert into APP.PROVINCES(country_id,name) values (2,'Hawaii');
insert into APP.PROVINCES(country_id,name) values (2,'Idaho');
insert into APP.PROVINCES(country_id,name) values (2,'Illinois');
insert into APP.PROVINCES(country_id,name) values (2,'Indiana');
insert into APP.PROVINCES(country_id,name) values (2,'Iowa');
insert into APP.PROVINCES(country_id,name) values (2,'Kansas');
insert into APP.PROVINCES(country_id,name) values (2,'Kentucky');
insert into APP.PROVINCES(country_id,name) values (2,'Louisiana');
insert into APP.PROVINCES(country_id,name) values (2,'Maine');
insert into APP.PROVINCES(country_id,name) values (2,'Maryland');
insert into APP.PROVINCES(country_id,name) values (2,'Massachusetts');
insert into APP.PROVINCES(country_id,name) values (2,'Michigan');
insert into APP.PROVINCES(country_id,name) values (2,'Minnesota');
insert into APP.PROVINCES(country_id,name) values (2,'Mississippi');
insert into APP.PROVINCES(country_id,name) values (2,'Missouri');
insert into APP.PROVINCES(country_id,name) values (2,'Montana');
insert into APP.PROVINCES(country_id,name) values (2,'Nebraska');
insert into APP.PROVINCES(country_id,name) values (2,'Nevada');
insert into APP.PROVINCES(country_id,name) values (2,'New Hampshire');
insert into APP.PROVINCES(country_id,name) values (2,'New Jersey');
insert into APP.PROVINCES(country_id,name) values (2,'New Mexico');
insert into APP.PROVINCES(country_id,name) values (2,'New York');
insert into APP.PROVINCES(country_id,name) values (2,'North Carolina');
insert into APP.PROVINCES(country_id,name) values (2,'North Dakota');
insert into APP.PROVINCES(country_id,name) values (2,'Ohio');
insert into APP.PROVINCES(country_id,name) values (2,'Oklahoma');
insert into APP.PROVINCES(country_id,name) values (2,'Oregon');
insert into APP.PROVINCES(country_id,name) values (2,'Pennsylvania');
insert into APP.PROVINCES(country_id,name) values (2,'Rhode Island');
insert into APP.PROVINCES(country_id,name) values (2,'South Carolina');
insert into APP.PROVINCES(country_id,name) values (2,'South Dakota');
insert into APP.PROVINCES(country_id,name) values (2,'Tennessee');
insert into APP.PROVINCES(country_id,name) values (2,'Texas');
insert into APP.PROVINCES(country_id,name) values (2,'Utah');
insert into APP.PROVINCES(country_id,name) values (2,'Vermont');
insert into APP.PROVINCES(country_id,name) values (2,'Virginia');
insert into APP.PROVINCES(country_id,name) values (2,'Washington');
insert into APP.PROVINCES(country_id,name) values (2,'West Virginia');
insert into APP.PROVINCES(country_id,name) values (2,'Wisconsin');
insert into APP.PROVINCES(country_id,name) values (2,'Wyoming');

select * from APP.PROVINCES;
